// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWardrobe.Persistence;

#nullable disable

namespace MyWardrobe2.Migrations
{
    [DbContext(typeof(MyWardrobeDbContext))]
    partial class MyWardrobeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MyWardrobe.Models.WardrobeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastTimeUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WardrobeItemUsage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WardrobeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
